# Generated by Django 5.0
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_description', models.TextField(blank=True)),
                ('main_pain_point', models.TextField(blank=True)),
                ('current_solutions', models.TextField(blank=True)),
                ('budget_range', models.CharField(blank=True, max_length=50)),
                ('timeline', models.CharField(blank=True, max_length=50)),
                ('decision_maker', models.BooleanField(default=False)),
                ('recommended_solution', models.CharField(blank=True, max_length=100)),
                ('secondary_solutions', models.JSONField(default=list)),
                ('diagnosis_summary', models.TextField(blank=True)),
                ('diagnosis_date', models.DateTimeField(blank=True, null=True)),
                ('wizard_completed', models.BooleanField(default=False)),
                ('wizard_completed_date', models.DateTimeField(blank=True, null=True)),
                ('total_interactions', models.IntegerField(default=0)),
                ('total_chat_messages', models.IntegerField(default=0)),
                ('last_interaction', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lead_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lead Profile',
                'verbose_name_plural': 'Lead Profiles',
                'db_table': 'lead_profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interaction_type', models.CharField(choices=[('wizard_start', 'Started Wizard'), ('wizard_step', 'Completed Wizard Step'), ('wizard_complete', 'Completed Wizard'), ('chat_message', 'Chat Message'), ('page_view', 'Page View'), ('document_download', 'Document Download'), ('cta_click', 'CTA Click'), ('email_open', 'Email Open'), ('email_click', 'Email Click')], max_length=30)),
                ('data', models.JSONField(default=dict)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='leads.leadprofile')),
            ],
            options={
                'verbose_name': 'Lead Interaction',
                'verbose_name_plural': 'Lead Interactions',
                'db_table': 'lead_interactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_notes', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='leads.leadprofile')),
            ],
            options={
                'verbose_name': 'Lead Note',
                'verbose_name_plural': 'Lead Notes',
                'db_table': 'lead_notes',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='leadinteraction',
            index=models.Index(fields=['lead', '-created_at'], name='lead_intera_lead_id_7d5e8e_idx'),
        ),
        migrations.AddIndex(
            model_name='leadinteraction',
            index=models.Index(fields=['interaction_type'], name='lead_intera_interac_5c0e7e_idx'),
        ),
        migrations.AddIndex(
            model_name='leadinteraction',
            index=models.Index(fields=['session_id'], name='lead_intera_session_d3a1b2_idx'),
        ),
    ]
