# Generated by Django 5.0
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WizardStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField(unique=True)),
                ('title_en', models.CharField(max_length=255)),
                ('title_es', models.CharField(max_length=255)),
                ('description_en', models.TextField(blank=True)),
                ('description_es', models.TextField(blank=True)),
                ('quick_win_en', models.TextField(blank=True)),
                ('quick_win_es', models.TextField(blank=True)),
                ('question_type', models.CharField(choices=[('single_choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice'), ('text', 'Free Text'), ('scale', 'Scale 1-10')], max_length=20)),
                ('options', models.JSONField(default=list)),
                ('placeholder_en', models.CharField(blank=True, max_length=255)),
                ('placeholder_es', models.CharField(blank=True, max_length=255)),
                ('is_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Wizard Step',
                'verbose_name_plural': 'Wizard Steps',
                'db_table': 'wizard_steps',
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='WizardSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('current_step', models.IntegerField(default=1)),
                ('total_steps', models.IntegerField(default=6)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wizard_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wizard Session',
                'verbose_name_plural': 'Wizard Sessions',
                'db_table': 'wizard_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WizardResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('response_value', models.TextField()),
                ('response_data', models.JSONField(default=dict)),
                ('time_spent_seconds', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='wizard.wizardsession')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wizard.wizardstep')),
            ],
            options={
                'verbose_name': 'Wizard Response',
                'verbose_name_plural': 'Wizard Responses',
                'db_table': 'wizard_responses',
                'unique_together': {('session', 'step')},
            },
        ),
        migrations.CreateModel(
            name='DiagnosisResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('primary_solution', models.CharField(choices=[('data_room_audit', 'Data Room para Auditorías'), ('gap_analysis', 'Corporate Doc Gap Analysis'), ('deal_teaser', 'Deal Teaser para Licitaciones'), ('data_room_prep', 'Data Room Prep para Due Diligence'), ('deal_visor', 'Deal Visor para Monitoreo de Contratos'), ('smart_data_room', 'Smart Data Room con Firma Digital')], max_length=50)),
                ('secondary_solutions', models.JSONField(default=list)),
                ('diagnosis_summary_en', models.TextField(blank=True)),
                ('diagnosis_summary_es', models.TextField(blank=True)),
                ('pain_points_identified', models.JSONField(default=list)),
                ('recommended_features', models.JSONField(default=list)),
                ('urgency_score', models.IntegerField(default=0)),
                ('fit_score', models.IntegerField(default=0)),
                ('personalized_pitch_en', models.TextField(blank=True)),
                ('personalized_pitch_es', models.TextField(blank=True)),
                ('next_steps', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='wizard.wizardsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Diagnosis Result',
                'verbose_name_plural': 'Diagnosis Results',
                'db_table': 'diagnosis_results',
            },
        ),
    ]
